# Generated by Django 5.2.8 on 2025-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_idea_quizquestion_resource_simulationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='resource_url',
            field=models.URLField(blank=True, help_text='URL vers une ressource pédagogique', null=True),
        ),
    ]
